import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates and downloads a clean, professional PDF Health Report for PulseCare AI
 * Developed by Vaibhava G
 */
export const generateHealthReportPDF = (patientData = {}) => {
  const doc = new jsPDF();
  const primaryColor = [5, 150, 105]; // Emerald-600

  // Header Banner
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("PulseCare AI – Clinical Health Summary", 14, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Architected & Developed by Vaibhava G", 14, 27);

  // Date Generated
  const dateStr = new Date().toLocaleDateString("en-US", {
    dateStyle: "full",
  });
  doc.text(`Report Date: ${dateStr}`, 145, 27);

  // Patient Info Card
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Information", 14, 45);

  const patientName = patientData.name || "Patient Overview";
  const patientEmail = patientData.email || "N/A";
  const bloodGroup = patientData.bloodGroup || "O+";
  const allergies = patientData.allergies || "Penicillin";

  autoTable(doc, {
    startY: 50,
    head: [["Field", "Clinical Detail"]],
    body: [
      ["Patient Name", patientName],
      ["Email Address", patientEmail],
      ["Blood Group", bloodGroup],
      ["Known Allergies", allergies],
      ["Emergency Contact", patientData.emergencyContactName ? `${patientData.emergencyContactName} (${patientData.emergencyContactPhone || ""})` : "Jane Doe (+1 555-019-2834)"],
    ],
    theme: "striped",
    headStyles: { fillStyle: "F", fillColor: primaryColor, textColor: 255, fontStyle: "bold" },
  });

  // Recent Vital Signs Table
  const currentY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Recent Biometric Vital Logs", 14, currentY);

  autoTable(doc, {
    startY: currentY + 5,
    head: [["Metric", "Recorded Value", "Clinical Status", "Timestamp"]],
    body: [
      ["Blood Pressure", "120/80 mmHg", "Optimal", "Today, 08:30 AM"],
      ["Resting Heart Rate", "72 BPM", "Normal Range", "Yesterday, 06:15 PM"],
      ["Blood Glucose", "95 mg/dL", "Fasting Normal", "2 days ago"],
      ["Body Temperature", "98.6 °F", "Normal", "3 days ago"],
    ],
    theme: "grid",
    headStyles: { fillColor: [13, 148, 136] }, // Teal-600
  });

  // Active Prescriptions Summary
  const rxY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Active Prescriptions & Dosage", 14, rxY);

  autoTable(doc, {
    startY: rxY + 5,
    head: [["Medication Name", "Dosage & Frequency", "Prescribing Physician", "Status"]],
    body: [
      ["Amoxicillin 500mg", "1 Capsule - 2x Daily", "Dr. Sarah Johnson", "Active"],
      ["Lisinopril 10mg", "1 Tablet - Every Morning", "Dr. Michael Chen", "Active"],
      ["Metformin 850mg", "1 Tablet - With Dinner", "Dr. Sarah Johnson", "Active"],
    ],
    theme: "striped",
    headStyles: { fillColor: primaryColor },
  });

  // Footer
  const footerY = 280;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Confidential Healthcare Document – Generated by PulseCare AI (Developed by Vaibhava G)", 14, footerY);

  doc.save(`PulseCare_Health_Report_${patientName.replace(/\s+/g, "_")}.pdf`);
};
